In [60]:
import numpy as np 
import pandas as pd 
import json

In [61]:
import warnings 
warnings.filterwarnings('ignore')

# NOTE- 1 
- as we r using kaggle dataset and not scraping from scratch 
 we r directly loading the csv file using read csv

In [62]:
df = pd.read_csv(r"C:\Users\devender bahadur\Downloads\dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

# UNDERSTANDING BASIC INFO ABOUT OUR DATA

In [63]:
df.shape

(10000, 8)

In [64]:
df.size

80000

In [65]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [66]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [68]:
df.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [69]:
# per column count of missing/null values
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [70]:
# whole df count of null values
df.isnull().sum().sum()

np.int64(6826)

In [71]:
print(f'Size of dataset: ', df.size)
print(f'Total Null Values in the dataset: ', df.isnull().sum().sum())
print(f'Total Duplicate Records: ', df.duplicated().sum())
print(f'Shape of dataset: ', df.shape)
print(f'Basic Info of Dataset: ')
print(df.info())

Size of dataset:  80000
Total Null Values in the dataset:  6826
Total Duplicate Records:  0
Shape of dataset:  (10000, 8)
Basic Info of Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB
None

# NOTE - 2
- now that we loaded our data in python
- we also understood the data , null values
- its time to clean data i.e missing values and manipulate our data

In [72]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [73]:
if (df.columns != df.columns.str.strip()).any():
    print('Trim required')
else:
    print('no')

no

In [74]:
# Show list of unstripped column names
dirty_cols = df.columns[df.columns != df.columns.str.strip()].tolist()
print("Columns that need trimming:", dirty_cols)

Columns that need trimming: []

# DATA CLEANING 

##  NOTE-3
- chnging dtypes appropriately as right now we have everything in strings 
- removing unwanted columns or rows
- rename columns to proper names
- extracting extra details from existing columns i.e manipulating data 
- duplicates handling
- simplifying rows/categorise rows

In [75]:
#changing location to dining option 

df['Dining Option'] = df['Location']
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Dining Option
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,Takeaway
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,In-store
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,In-store
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,UNKNOWN
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,In-store
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30,UNKNOWN
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,NaN
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,NaN
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,NaN
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,In-store

In [76]:
df.drop('Location',axis=1,inplace = True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,2023-09-08,Takeaway
1,TXN_4977031,Cake,4,3.0,12.0,Cash,2023-05-16,In-store
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,2023-07-19,In-store
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,2023-04-27,UNKNOWN
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,2023-06-11,In-store
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,2023-08-30,UNKNOWN
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,2023-06-02,NaN
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,2023-03-02,NaN
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,2023-12-02,NaN
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,2023-11-07,In-store

# Dtype conversion

In [77]:

df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce') 
text_cols = ['Item', 'Payment Method', 'Dining Option']
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

df['Quantity'] = pd.to_numeric(df['Quantity'].astype(str).str.strip(), errors='coerce')
for col in ['Price Per Unit', 'Total Spent']:
    # Clean out currency signs ($), commas, and spaces first
    df[col] = df[col].astype(str).str.replace('$', '', regex=False).str.strip()
    df[col] = pd.to_numeric(df[col], errors='coerce')

print(df.dtypes)

Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Transaction Date    datetime64[ns]
Dining Option               object
dtype: object

In [78]:
# extract day of the week using transaction date column 

df['Transaction Month'] = df['Transaction Date'].dt.month_name()
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,2023-07-19,In-Store,July
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,2023-04-27,Unknown,April
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Nan,2023-08-30,Unknown,August
9996,TXN_9659401,Nan,3.0,NaN,3.0,Digital Wallet,2023-06-02,Nan,June
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Nan,March
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,2023-12-02,Nan,December
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November

In [79]:
df['Transaction weekday'] =df['Transaction Date'].dt.day_name()
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,2023-07-19,In-Store,July,Wednesday
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,2023-04-27,Unknown,April,Thursday
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday
...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Nan,2023-08-30,Unknown,August,Wednesday
9996,TXN_9659401,Nan,3.0,NaN,3.0,Digital Wallet,2023-06-02,Nan,June,Friday
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Nan,March,Thursday
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,2023-12-02,Nan,December,Saturday
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November,Tuesday

# DUPLICATE RECORDS IN DF

In [80]:
# Count total exact duplicate rows
print("Exact duplicate rows:", df.duplicated().sum())

Exact duplicate rows: 0

In [81]:
# Check for duplicate Transaction IDs specifically
print("Duplicate Transaction IDs:", df['Transaction ID'].duplicated().sum())

Duplicate Transaction IDs: 0

# missing values treatment in payment category column

In [82]:
# Step 1: Clean and standardize text to Title Case
df['Payment Method'] = df['Payment Method'].astype(str).str.strip().str.title()

# Step 2: Replace invalid placeholders with 'Unspecified'
invalid_values = ['Error', 'Unknown', '0', 'Nan', 'None', '']
df['Payment Method'] = df['Payment Method'].replace(invalid_values, 'Unspecified')

# Step 3: Handle any remaining actual NaN values
df['Payment Method'] = df['Payment Method'].fillna('Unspecified')

df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,2023-07-19,In-Store,July,Wednesday
3,TXN_7034554,Salad,2.0,5.0,10.0,Unspecified,2023-04-27,Unknown,April,Thursday
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday
...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unspecified,2023-08-30,Unknown,August,Wednesday
9996,TXN_9659401,Nan,3.0,NaN,3.0,Digital Wallet,2023-06-02,Nan,June,Friday
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Nan,March,Thursday
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,2023-12-02,Nan,December,Saturday
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November,Tuesday

In [83]:
df.isnull().sum().sum()

np.int64(2894)

In [84]:
print(df.isna().sum())

Transaction ID           0
Item                     0
Quantity               479
Price Per Unit         533
Total Spent            502
Payment Method           0
Transaction Date       460
Dining Option            0
Transaction Month      460
Transaction weekday    460
dtype: int64

# working on Transaction date column

In [85]:
# Forward fill missing dates from preceding transactions
df['Transaction Date'] = df['Transaction Date'].ffill()

# Recalculate derived month and weekday
df['Transaction Month'] = df['Transaction Date'].dt.month_name()
df['Transaction weekday'] = df['Transaction Date'].dt.day_name()

In [86]:
# Drop rows where Transaction Date is NaT
df = df.dropna(subset=['Transaction Date'])

# Re-derive month and weekday
df['Transaction Month'] = df['Transaction Date'].dt.month_name()
df['Transaction weekday'] = df['Transaction Date'].dt.day_name()

In [87]:
print(df.isna().sum())

Transaction ID           0
Item                     0
Quantity               479
Price Per Unit         533
Total Spent            502
Payment Method           0
Transaction Date         0
Dining Option            0
Transaction Month        0
Transaction weekday      0
dtype: int64

# working on numerical columns missing values

In [88]:
# replacing records tht have unknown , error, 0 from payment status 

import numpy as np

# Step 1: Use exact row-level math where 2 out of 3 numbers exist
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])
df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])

# Step 2: Fill remaining missing Price Per Unit using median price of that specific Item
df['Price Per Unit'] = df['Price Per Unit'].fillna(
    df.groupby('Item')['Price Per Unit'].transform('median')
)

# Step 3: Re-apply row math after Price Per Unit is imputed
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])
df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])

# Step 4: Final fallback for remaining Quantity (default to 1) and calculate final Total Spent
df['Quantity'] = df['Quantity'].fillna(1)
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

# RESULT AFTER DATA CLEANING

In [89]:
print(df.isna().sum())

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method         0
Transaction Date       0
Dining Option          0
Transaction Month      0
Transaction weekday    0
dtype: int64

In [90]:
df.isnull().sum().sum()

np.int64(0)

In [91]:
# from 10000,8 to 10000, 10 shape od df
df.shape

(10000, 10)

In [92]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19,In-Store,July,Wednesday
3,TXN_7034554,Salad,2.0,5.0,10.0,Unspecified,2023-04-27,Unknown,April,Thursday
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday
...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unspecified,2023-08-30,Unknown,August,Wednesday
9996,TXN_9659401,Nan,3.0,1.0,3.0,Digital Wallet,2023-06-02,Nan,June,Friday
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Nan,March,Thursday
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,2023-12-02,Nan,December,Saturday
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November,Tuesday

# Categorical column DATA MANIPULATION

##  work on payment option column

In [93]:
# cash as offline / digital wallet or credit card as online 
df['Payment Category'] = df['Payment Method']
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday,Payment Category
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday,Credit Card
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday,Cash
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19,In-Store,July,Wednesday,Credit Card
3,TXN_7034554,Salad,2.0,5.0,10.0,Unspecified,2023-04-27,Unknown,April,Thursday,Unspecified
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday,Digital Wallet
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unspecified,2023-08-30,Unknown,August,Wednesday,Unspecified
9996,TXN_9659401,Nan,3.0,1.0,3.0,Digital Wallet,2023-06-02,Nan,June,Friday,Digital Wallet
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Nan,March,Thursday,Digital Wallet
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,2023-12-02,Nan,December,Saturday,Digital Wallet
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November,Tuesday,Cash

In [94]:
# List all categorical text columns
cat_cols = ['Item', 'Payment Method', 'Dining Option', 'Payment Category']

for col in cat_cols:
    # Convert to string and clean extra whitespace
    df[col] = df[col].astype(str).str.strip()
    
    # Replace string artifacts ('Nan', 'UNKNOWN', 'Unknown', '0', 'None', etc.) with 'Unspecified'
    df[col] = df[col].replace(
        ['Nan', 'nan', 'UNKNOWN', 'Unknown', 'ERROR', 'Error', '0', 'None', '', 'nan'], 
        'Unspecified'
    )

    # Handle true NaN values if any exist
    df[col] = df[col].fillna('Unspecified')

In [95]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday,Payment Category
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday,Credit Card
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday,Cash
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19,In-Store,July,Wednesday,Credit Card
3,TXN_7034554,Salad,2.0,5.0,10.0,Unspecified,2023-04-27,Unspecified,April,Thursday,Unspecified
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday,Digital Wallet
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unspecified,2023-08-30,Unspecified,August,Wednesday,Unspecified
9996,TXN_9659401,Unspecified,3.0,1.0,3.0,Digital Wallet,2023-06-02,Unspecified,June,Friday,Digital Wallet
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Unspecified,March,Thursday,Digital Wallet
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,2023-12-02,Unspecified,December,Saturday,Digital Wallet
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November,Tuesday,Cash

In [96]:
# Map Payment Methods to Offline / Online categories
payment_map = {
    'Cash': 'Offline',
    'Credit Card': 'Online',
    'Digital Wallet': 'Online',
    'Unspecified': 'Unspecified'
}

df['Payment Category'] = df['Payment Method'].map(payment_map).fillna('Unspecified')

In [97]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday,Payment Category
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday,Online
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday,Offline
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19,In-Store,July,Wednesday,Online
3,TXN_7034554,Salad,2.0,5.0,10.0,Unspecified,2023-04-27,Unspecified,April,Thursday,Unspecified
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday,Online
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unspecified,2023-08-30,Unspecified,August,Wednesday,Unspecified
9996,TXN_9659401,Unspecified,3.0,1.0,3.0,Digital Wallet,2023-06-02,Unspecified,June,Friday,Online
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Unspecified,March,Thursday,Online
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,2023-12-02,Unspecified,December,Saturday,Online
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November,Tuesday,Offline

In [98]:
# categorise food items as eatables and drinks 
print(df['Item'].unique())

['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'Unspecified' 'Sandwich'
 'Juice' 'Tea']

In [99]:
# 1. Define the item categorization map
item_category_map = {
    'Coffee': 'Drink',
    'Tea': 'Drink',
    'Juice': 'Drink',
    'Smoothie': 'Drink',
    'Cake': 'Eatable',
    'Cookie': 'Eatable',
    'Sandwich': 'Eatable',
    'Salad': 'Eatable',
    'Unspecified': 'Unspecified'
}

# 2. Create the new 'Item Category' column
df['Item Category'] = df['Item'].map(item_category_map).fillna('Unspecified')

df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday,Payment Category,Item Category
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday,Online,Drink
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday,Offline,Eatable
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19,In-Store,July,Wednesday,Online,Eatable
3,TXN_7034554,Salad,2.0,5.0,10.0,Unspecified,2023-04-27,Unspecified,April,Thursday,Unspecified,Eatable
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday,Online,Drink
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unspecified,2023-08-30,Unspecified,August,Wednesday,Unspecified,Drink
9996,TXN_9659401,Unspecified,3.0,1.0,3.0,Digital Wallet,2023-06-02,Unspecified,June,Friday,Online,Unspecified
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02,Unspecified,March,Thursday,Online,Drink
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,2023-12-02,Unspecified,December,Saturday,Online,Eatable
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07,In-Store,November,Tuesday,Offline,Eatable

# numerical column manipulation

In [100]:
# Create a new column showing total sales amount per Transaction ID
df['ID Total Sales'] = df.groupby('Transaction ID')['Total Spent'].transform('sum')

In [101]:
# 1. Rename 'Total Spent' to 'Total Sales'
df = df.rename(columns={'Total Spent': 'Total Sales'})

# 2. Drop 'ID Total Sales' as total spent column calculates the same its better to drop
if 'ID Total Sales' in df.columns:
    df = df.drop(columns=['ID Total Sales'])

In [102]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Sales,Payment Method,Transaction Date,Dining Option,Transaction Month,Transaction weekday,Payment Category,Item Category
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08,Takeaway,September,Friday,Online,Drink
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16,In-Store,May,Tuesday,Offline,Eatable
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19,In-Store,July,Wednesday,Online,Eatable
3,TXN_7034554,Salad,2.0,5.0,10.0,Unspecified,2023-04-27,Unspecified,April,Thursday,Unspecified,Eatable
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11,In-Store,June,Sunday,Online,Drink

# cleaning manipulation done

In [103]:
print(f'Size of dataset: ', df.size)
print(f'Total Null Values in the dataset: ', df.isnull().sum().sum())
print(f'Total Duplicate Records: ', df.duplicated().sum())
print(f'Shape of dataset: ', df.shape)
print(f'Basic Info of Dataset: ')
print(df.info())

Size of dataset:  120000
Total Null Values in the dataset:  0
Total Duplicate Records:  0
Shape of dataset:  (10000, 12)
Basic Info of Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       10000 non-null  object
 1   Item                 10000 non-null  object
 2   Quantity             10000 non-null  float64
 3   Price Per Unit       10000 non-null  float64
 4   Total Sales          10000 non-null  float64
 5   Payment Method       10000 non-null  object
 6   Transaction Date     10000 non-null  datetime64[ns]
 7   Dining Option        10000 non-null  object
 8   Transaction Month    10000 non-null  object
 9   Transaction weekday  10000 non-null  object
 10  Payment Category     10000 non-null  object
 11  Item Category        10000 non-null  object
dtypes: datetime64[ns](1), float64(3), object(8)
memory usage: 937.6+ KB
None

In [51]:
# Export clean dataset
df.to_csv('cleaned_cafe_sales_final.csv', index=False)
print("Saved successfully! Total rows:", len(df))

Saved successfully! Total rows: 10000